/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.iisys.liferay.portlet.camundaACM.caseOverview.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CaseInstance service. Represents a row in the &quot;CamundaACM_CaseInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.iisys.liferay.portlet.camundaACM.caseOverview.model.impl.CaseInstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.iisys.liferay.portlet.camundaACM.caseOverview.model.impl.CaseInstanceImpl}.
 * </p>
 *
 * @author Christian OchsenkÃ¼hn
 * @see CaseInstance
 * @see de.iisys.liferay.portlet.camundaACM.caseOverview.model.impl.CaseInstanceImpl
 * @see de.iisys.liferay.portlet.camundaACM.caseOverview.model.impl.CaseInstanceModelImpl
 * @generated
 */
public interface CaseInstanceModel extends BaseModel<CaseInstance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a case instance model instance should use the {@link CaseInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this case instance.
	 *
	 * @return the primary key of this case instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this case instance.
	 *
	 * @param primaryKey the primary key of this case instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the liferay case instance ID of this case instance.
	 *
	 * @return the liferay case instance ID of this case instance
	 */
	public long getLiferayCaseInstanceId();

	/**
	 * Sets the liferay case instance ID of this case instance.
	 *
	 * @param liferayCaseInstanceId the liferay case instance ID of this case instance
	 */
	public void setLiferayCaseInstanceId(long liferayCaseInstanceId);

	/**
	 * Returns the company ID of this case instance.
	 *
	 * @return the company ID of this case instance
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this case instance.
	 *
	 * @param companyId the company ID of this case instance
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this case instance.
	 *
	 * @return the group ID of this case instance
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this case instance.
	 *
	 * @param groupId the group ID of this case instance
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this case instance.
	 *
	 * @return the user ID of this case instance
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this case instance.
	 *
	 * @param userId the user ID of this case instance
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this case instance.
	 *
	 * @return the user uuid of this case instance
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this case instance.
	 *
	 * @param userUuid the user uuid of this case instance
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this case instance.
	 *
	 * @return the create date of this case instance
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this case instance.
	 *
	 * @param createDate the create date of this case instance
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this case instance.
	 *
	 * @return the modified date of this case instance
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this case instance.
	 *
	 * @param modifiedDate the modified date of this case instance
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the case instance ID of this case instance.
	 *
	 * @return the case instance ID of this case instance
	 */
	@AutoEscape
	public String getCaseInstanceId();

	/**
	 * Sets the case instance ID of this case instance.
	 *
	 * @param caseInstanceId the case instance ID of this case instance
	 */
	public void setCaseInstanceId(String caseInstanceId);

	/**
	 * Returns the case definition key of this case instance.
	 *
	 * @return the case definition key of this case instance
	 */
	@AutoEscape
	public String getCaseDefinitionKey();

	/**
	 * Sets the case definition key of this case instance.
	 *
	 * @param caseDefinitionKey the case definition key of this case instance
	 */
	public void setCaseDefinitionKey(String caseDefinitionKey);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CaseInstance caseInstance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CaseInstance> toCacheModel();

	@Override
	public CaseInstance toEscapedModel();

	@Override
	public CaseInstance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}